/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.riferrei.kafka.connect.pulsar;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroGenInnerType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8803923808981876438L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroGenInnerType\",\"namespace\":\"com.riferrei.kafka.connect.pulsar\",\"fields\":[{\"name\":\"doubleField\",\"type\":\"double\"},{\"name\":\"arrayField\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"enumField\",\"type\":{\"type\":\"enum\",\"name\":\"AvroGenMultipleOptions\",\"symbols\":[\"FirstOption\",\"SecondOption\",\"ThirdOption\",\"FourthOption\"],\"default\":\"FirstOption\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroGenInnerType> ENCODER =
      new BinaryMessageEncoder<AvroGenInnerType>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroGenInnerType> DECODER =
      new BinaryMessageDecoder<AvroGenInnerType>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroGenInnerType> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroGenInnerType> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroGenInnerType> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroGenInnerType>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroGenInnerType to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroGenInnerType from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroGenInnerType instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroGenInnerType fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public double doubleField;
  @Deprecated public java.util.List<java.lang.CharSequence> arrayField;
  @Deprecated public com.riferrei.kafka.connect.pulsar.AvroGenMultipleOptions enumField;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroGenInnerType() {}

  /**
   * All-args constructor.
   * @param doubleField The new value for doubleField
   * @param arrayField The new value for arrayField
   * @param enumField The new value for enumField
   */
  public AvroGenInnerType(java.lang.Double doubleField, java.util.List<java.lang.CharSequence> arrayField, com.riferrei.kafka.connect.pulsar.AvroGenMultipleOptions enumField) {
    this.doubleField = doubleField;
    this.arrayField = arrayField;
    this.enumField = enumField;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return doubleField;
    case 1: return arrayField;
    case 2: return enumField;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: doubleField = (java.lang.Double)value$; break;
    case 1: arrayField = (java.util.List<java.lang.CharSequence>)value$; break;
    case 2: enumField = (com.riferrei.kafka.connect.pulsar.AvroGenMultipleOptions)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'doubleField' field.
   * @return The value of the 'doubleField' field.
   */
  public double getDoubleField() {
    return doubleField;
  }


  /**
   * Sets the value of the 'doubleField' field.
   * @param value the value to set.
   */
  public void setDoubleField(double value) {
    this.doubleField = value;
  }

  /**
   * Gets the value of the 'arrayField' field.
   * @return The value of the 'arrayField' field.
   */
  public java.util.List<java.lang.CharSequence> getArrayField() {
    return arrayField;
  }


  /**
   * Sets the value of the 'arrayField' field.
   * @param value the value to set.
   */
  public void setArrayField(java.util.List<java.lang.CharSequence> value) {
    this.arrayField = value;
  }

  /**
   * Gets the value of the 'enumField' field.
   * @return The value of the 'enumField' field.
   */
  public com.riferrei.kafka.connect.pulsar.AvroGenMultipleOptions getEnumField() {
    return enumField;
  }


  /**
   * Sets the value of the 'enumField' field.
   * @param value the value to set.
   */
  public void setEnumField(com.riferrei.kafka.connect.pulsar.AvroGenMultipleOptions value) {
    this.enumField = value;
  }

  /**
   * Creates a new AvroGenInnerType RecordBuilder.
   * @return A new AvroGenInnerType RecordBuilder
   */
  public static com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder newBuilder() {
    return new com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder();
  }

  /**
   * Creates a new AvroGenInnerType RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroGenInnerType RecordBuilder
   */
  public static com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder newBuilder(com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder other) {
    if (other == null) {
      return new com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder();
    } else {
      return new com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder(other);
    }
  }

  /**
   * Creates a new AvroGenInnerType RecordBuilder by copying an existing AvroGenInnerType instance.
   * @param other The existing instance to copy.
   * @return A new AvroGenInnerType RecordBuilder
   */
  public static com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder newBuilder(com.riferrei.kafka.connect.pulsar.AvroGenInnerType other) {
    if (other == null) {
      return new com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder();
    } else {
      return new com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroGenInnerType instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroGenInnerType>
    implements org.apache.avro.data.RecordBuilder<AvroGenInnerType> {

    private double doubleField;
    private java.util.List<java.lang.CharSequence> arrayField;
    private com.riferrei.kafka.connect.pulsar.AvroGenMultipleOptions enumField;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.doubleField)) {
        this.doubleField = data().deepCopy(fields()[0].schema(), other.doubleField);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.arrayField)) {
        this.arrayField = data().deepCopy(fields()[1].schema(), other.arrayField);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.enumField)) {
        this.enumField = data().deepCopy(fields()[2].schema(), other.enumField);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroGenInnerType instance
     * @param other The existing instance to copy.
     */
    private Builder(com.riferrei.kafka.connect.pulsar.AvroGenInnerType other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.doubleField)) {
        this.doubleField = data().deepCopy(fields()[0].schema(), other.doubleField);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.arrayField)) {
        this.arrayField = data().deepCopy(fields()[1].schema(), other.arrayField);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.enumField)) {
        this.enumField = data().deepCopy(fields()[2].schema(), other.enumField);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'doubleField' field.
      * @return The value.
      */
    public double getDoubleField() {
      return doubleField;
    }


    /**
      * Sets the value of the 'doubleField' field.
      * @param value The value of 'doubleField'.
      * @return This builder.
      */
    public com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder setDoubleField(double value) {
      validate(fields()[0], value);
      this.doubleField = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'doubleField' field has been set.
      * @return True if the 'doubleField' field has been set, false otherwise.
      */
    public boolean hasDoubleField() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'doubleField' field.
      * @return This builder.
      */
    public com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder clearDoubleField() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'arrayField' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getArrayField() {
      return arrayField;
    }


    /**
      * Sets the value of the 'arrayField' field.
      * @param value The value of 'arrayField'.
      * @return This builder.
      */
    public com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder setArrayField(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.arrayField = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'arrayField' field has been set.
      * @return True if the 'arrayField' field has been set, false otherwise.
      */
    public boolean hasArrayField() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'arrayField' field.
      * @return This builder.
      */
    public com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder clearArrayField() {
      arrayField = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'enumField' field.
      * @return The value.
      */
    public com.riferrei.kafka.connect.pulsar.AvroGenMultipleOptions getEnumField() {
      return enumField;
    }


    /**
      * Sets the value of the 'enumField' field.
      * @param value The value of 'enumField'.
      * @return This builder.
      */
    public com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder setEnumField(com.riferrei.kafka.connect.pulsar.AvroGenMultipleOptions value) {
      validate(fields()[2], value);
      this.enumField = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'enumField' field has been set.
      * @return True if the 'enumField' field has been set, false otherwise.
      */
    public boolean hasEnumField() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'enumField' field.
      * @return This builder.
      */
    public com.riferrei.kafka.connect.pulsar.AvroGenInnerType.Builder clearEnumField() {
      enumField = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroGenInnerType build() {
      try {
        AvroGenInnerType record = new AvroGenInnerType();
        record.doubleField = fieldSetFlags()[0] ? this.doubleField : (java.lang.Double) defaultValue(fields()[0]);
        record.arrayField = fieldSetFlags()[1] ? this.arrayField : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[1]);
        record.enumField = fieldSetFlags()[2] ? this.enumField : (com.riferrei.kafka.connect.pulsar.AvroGenMultipleOptions) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroGenInnerType>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroGenInnerType>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroGenInnerType>
    READER$ = (org.apache.avro.io.DatumReader<AvroGenInnerType>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeDouble(this.doubleField);

    long size0 = this.arrayField.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.arrayField) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeEnum(this.enumField.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.doubleField = in.readDouble();

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.arrayField;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("arrayField").schema());
        this.arrayField = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

      this.enumField = com.riferrei.kafka.connect.pulsar.AvroGenMultipleOptions.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.doubleField = in.readDouble();
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.arrayField;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("arrayField").schema());
            this.arrayField = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        case 2:
          this.enumField = com.riferrei.kafka.connect.pulsar.AvroGenMultipleOptions.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










