/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.riferrei.kafka.connect.pulsar;
@org.apache.avro.specific.AvroGenerated
public enum AvroGenMultipleOptions implements org.apache.avro.generic.GenericEnumSymbol<AvroGenMultipleOptions> {
  FirstOption, SecondOption, ThirdOption, FourthOption  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AvroGenMultipleOptions\",\"namespace\":\"com.riferrei.kafka.connect.pulsar\",\"symbols\":[\"FirstOption\",\"SecondOption\",\"ThirdOption\",\"FourthOption\"],\"default\":\"FirstOption\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
