// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: complexType.proto

package com.riferrei.kafka.connect.pulsar;

public final class ProtoBufGenComplexType {
  private ProtoBufGenComplexType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoBufComplexTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.riferrei.kafka.connect.pulsar.ProtoBufComplexType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string stringField = 1;</code>
     */
    java.lang.String getStringField();
    /**
     * <code>string stringField = 1;</code>
     */
    com.google.protobuf.ByteString
        getStringFieldBytes();

    /**
     * <code>bool booleanField = 2;</code>
     */
    boolean getBooleanField();

    /**
     * <code>bytes bytesField = 3;</code>
     */
    com.google.protobuf.ByteString getBytesField();

    /**
     * <code>int32 intField = 4;</code>
     */
    int getIntField();

    /**
     * <code>int64 longField = 5;</code>
     */
    long getLongField();

    /**
     * <code>float floatField = 6;</code>
     */
    float getFloatField();

    /**
     * <code>double doubleField = 7;</code>
     */
    double getDoubleField();

    /**
     * <code>map&lt;string, double&gt; mapField = 8;</code>
     */
    int getMapFieldCount();
    /**
     * <code>map&lt;string, double&gt; mapField = 8;</code>
     */
    boolean containsMapField(
        java.lang.String key);
    /**
     * Use {@link #getMapFieldMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Double>
    getMapField();
    /**
     * <code>map&lt;string, double&gt; mapField = 8;</code>
     */
    java.util.Map<java.lang.String, java.lang.Double>
    getMapFieldMap();
    /**
     * <code>map&lt;string, double&gt; mapField = 8;</code>
     */

    double getMapFieldOrDefault(
        java.lang.String key,
        double defaultValue);
    /**
     * <code>map&lt;string, double&gt; mapField = 8;</code>
     */

    double getMapFieldOrThrow(
        java.lang.String key);

    /**
     * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
     */
    boolean hasInnerField();
    /**
     * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
     */
    com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType getInnerField();
    /**
     * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
     */
    com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerTypeOrBuilder getInnerFieldOrBuilder();
  }
  /**
   * Protobuf type {@code com.riferrei.kafka.connect.pulsar.ProtoBufComplexType}
   */
  public  static final class ProtoBufComplexType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.riferrei.kafka.connect.pulsar.ProtoBufComplexType)
      ProtoBufComplexTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoBufComplexType.newBuilder() to construct.
    private ProtoBufComplexType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoBufComplexType() {
      stringField_ = "";
      bytesField_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoBufComplexType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              stringField_ = s;
              break;
            }
            case 16: {

              booleanField_ = input.readBool();
              break;
            }
            case 26: {

              bytesField_ = input.readBytes();
              break;
            }
            case 32: {

              intField_ = input.readInt32();
              break;
            }
            case 40: {

              longField_ = input.readInt64();
              break;
            }
            case 53: {

              floatField_ = input.readFloat();
              break;
            }
            case 57: {

              doubleField_ = input.readDouble();
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) != 0)) {
                mapField_ = com.google.protobuf.MapField.newMapField(
                    MapFieldDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000080;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
              mapField__ = input.readMessage(
                  MapFieldDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              mapField_.getMutableMap().put(
                  mapField__.getKey(), mapField__.getValue());
              break;
            }
            case 74: {
              com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.Builder subBuilder = null;
              if (innerField_ != null) {
                subBuilder = innerField_.toBuilder();
              }
              innerField_ = input.readMessage(com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(innerField_);
                innerField_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetMapField();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.class, com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.Builder.class);
    }

    public interface ProtoBufInnerTypeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>double doubleField = 1;</code>
       */
      double getDoubleField();

      /**
       * <code>repeated string arrayField = 2;</code>
       */
      java.util.List<java.lang.String>
          getArrayFieldList();
      /**
       * <code>repeated string arrayField = 2;</code>
       */
      int getArrayFieldCount();
      /**
       * <code>repeated string arrayField = 2;</code>
       */
      java.lang.String getArrayField(int index);
      /**
       * <code>repeated string arrayField = 2;</code>
       */
      com.google.protobuf.ByteString
          getArrayFieldBytes(int index);

      /**
       * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions enumField = 3;</code>
       */
      int getEnumFieldValue();
      /**
       * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions enumField = 3;</code>
       */
      com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions getEnumField();
    }
    /**
     * Protobuf type {@code com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType}
     */
    public  static final class ProtoBufInnerType extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType)
        ProtoBufInnerTypeOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ProtoBufInnerType.newBuilder() to construct.
      private ProtoBufInnerType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ProtoBufInnerType() {
        arrayField_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        enumField_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ProtoBufInnerType(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {

                doubleField_ = input.readDouble();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                  arrayField_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000002;
                }
                arrayField_.add(s);
                break;
              }
              case 24: {
                int rawValue = input.readEnum();

                enumField_ = rawValue;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) != 0)) {
            arrayField_ = arrayField_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_ProtoBufInnerType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_ProtoBufInnerType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.class, com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.Builder.class);
      }

      /**
       * Protobuf enum {@code com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions}
       */
      public enum ProtoBufMultipleOptions
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>FIRST_OPTION = 0;</code>
         */
        FIRST_OPTION(0),
        /**
         * <code>SECOND_OPTION = 1;</code>
         */
        SECOND_OPTION(1),
        /**
         * <code>THIRD_OPTION = 2;</code>
         */
        THIRD_OPTION(2),
        /**
         * <code>FOURTH_OPTION = 3;</code>
         */
        FOURTH_OPTION(3),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>FIRST_OPTION = 0;</code>
         */
        public static final int FIRST_OPTION_VALUE = 0;
        /**
         * <code>SECOND_OPTION = 1;</code>
         */
        public static final int SECOND_OPTION_VALUE = 1;
        /**
         * <code>THIRD_OPTION = 2;</code>
         */
        public static final int THIRD_OPTION_VALUE = 2;
        /**
         * <code>FOURTH_OPTION = 3;</code>
         */
        public static final int FOURTH_OPTION_VALUE = 3;


        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static ProtoBufMultipleOptions valueOf(int value) {
          return forNumber(value);
        }

        public static ProtoBufMultipleOptions forNumber(int value) {
          switch (value) {
            case 0: return FIRST_OPTION;
            case 1: return SECOND_OPTION;
            case 2: return THIRD_OPTION;
            case 3: return FOURTH_OPTION;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ProtoBufMultipleOptions>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            ProtoBufMultipleOptions> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<ProtoBufMultipleOptions>() {
                public ProtoBufMultipleOptions findValueByNumber(int number) {
                  return ProtoBufMultipleOptions.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.getDescriptor().getEnumTypes().get(0);
        }

        private static final ProtoBufMultipleOptions[] VALUES = values();

        public static ProtoBufMultipleOptions valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private ProtoBufMultipleOptions(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions)
      }

      private int bitField0_;
      public static final int DOUBLEFIELD_FIELD_NUMBER = 1;
      private double doubleField_;
      /**
       * <code>double doubleField = 1;</code>
       */
      public double getDoubleField() {
        return doubleField_;
      }

      public static final int ARRAYFIELD_FIELD_NUMBER = 2;
      private com.google.protobuf.LazyStringList arrayField_;
      /**
       * <code>repeated string arrayField = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getArrayFieldList() {
        return arrayField_;
      }
      /**
       * <code>repeated string arrayField = 2;</code>
       */
      public int getArrayFieldCount() {
        return arrayField_.size();
      }
      /**
       * <code>repeated string arrayField = 2;</code>
       */
      public java.lang.String getArrayField(int index) {
        return arrayField_.get(index);
      }
      /**
       * <code>repeated string arrayField = 2;</code>
       */
      public com.google.protobuf.ByteString
          getArrayFieldBytes(int index) {
        return arrayField_.getByteString(index);
      }

      public static final int ENUMFIELD_FIELD_NUMBER = 3;
      private int enumField_;
      /**
       * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions enumField = 3;</code>
       */
      public int getEnumFieldValue() {
        return enumField_;
      }
      /**
       * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions enumField = 3;</code>
       */
      public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions getEnumField() {
        @SuppressWarnings("deprecation")
        com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions result = com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions.valueOf(enumField_);
        return result == null ? com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (doubleField_ != 0D) {
          output.writeDouble(1, doubleField_);
        }
        for (int i = 0; i < arrayField_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, arrayField_.getRaw(i));
        }
        if (enumField_ != com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions.FIRST_OPTION.getNumber()) {
          output.writeEnum(3, enumField_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (doubleField_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, doubleField_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < arrayField_.size(); i++) {
            dataSize += computeStringSizeNoTag(arrayField_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getArrayFieldList().size();
        }
        if (enumField_ != com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions.FIRST_OPTION.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(3, enumField_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType)) {
          return super.equals(obj);
        }
        com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType other = (com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType) obj;

        if (java.lang.Double.doubleToLongBits(getDoubleField())
            != java.lang.Double.doubleToLongBits(
                other.getDoubleField())) return false;
        if (!getArrayFieldList()
            .equals(other.getArrayFieldList())) return false;
        if (enumField_ != other.enumField_) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DOUBLEFIELD_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDoubleField()));
        if (getArrayFieldCount() > 0) {
          hash = (37 * hash) + ARRAYFIELD_FIELD_NUMBER;
          hash = (53 * hash) + getArrayFieldList().hashCode();
        }
        hash = (37 * hash) + ENUMFIELD_FIELD_NUMBER;
        hash = (53 * hash) + enumField_;
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType)
          com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerTypeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_ProtoBufInnerType_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_ProtoBufInnerType_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.class, com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.Builder.class);
        }

        // Construct using com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          doubleField_ = 0D;

          arrayField_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          enumField_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_ProtoBufInnerType_descriptor;
        }

        @java.lang.Override
        public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType getDefaultInstanceForType() {
          return com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.getDefaultInstance();
        }

        @java.lang.Override
        public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType build() {
          com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType buildPartial() {
          com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType result = new com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          result.doubleField_ = doubleField_;
          if (((bitField0_ & 0x00000002) != 0)) {
            arrayField_ = arrayField_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.arrayField_ = arrayField_;
          result.enumField_ = enumField_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType) {
            return mergeFrom((com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType other) {
          if (other == com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.getDefaultInstance()) return this;
          if (other.getDoubleField() != 0D) {
            setDoubleField(other.getDoubleField());
          }
          if (!other.arrayField_.isEmpty()) {
            if (arrayField_.isEmpty()) {
              arrayField_ = other.arrayField_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureArrayFieldIsMutable();
              arrayField_.addAll(other.arrayField_);
            }
            onChanged();
          }
          if (other.enumField_ != 0) {
            setEnumFieldValue(other.getEnumFieldValue());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private double doubleField_ ;
        /**
         * <code>double doubleField = 1;</code>
         */
        public double getDoubleField() {
          return doubleField_;
        }
        /**
         * <code>double doubleField = 1;</code>
         */
        public Builder setDoubleField(double value) {
          
          doubleField_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double doubleField = 1;</code>
         */
        public Builder clearDoubleField() {
          
          doubleField_ = 0D;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList arrayField_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureArrayFieldIsMutable() {
          if (!((bitField0_ & 0x00000002) != 0)) {
            arrayField_ = new com.google.protobuf.LazyStringArrayList(arrayField_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated string arrayField = 2;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getArrayFieldList() {
          return arrayField_.getUnmodifiableView();
        }
        /**
         * <code>repeated string arrayField = 2;</code>
         */
        public int getArrayFieldCount() {
          return arrayField_.size();
        }
        /**
         * <code>repeated string arrayField = 2;</code>
         */
        public java.lang.String getArrayField(int index) {
          return arrayField_.get(index);
        }
        /**
         * <code>repeated string arrayField = 2;</code>
         */
        public com.google.protobuf.ByteString
            getArrayFieldBytes(int index) {
          return arrayField_.getByteString(index);
        }
        /**
         * <code>repeated string arrayField = 2;</code>
         */
        public Builder setArrayField(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureArrayFieldIsMutable();
          arrayField_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string arrayField = 2;</code>
         */
        public Builder addArrayField(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureArrayFieldIsMutable();
          arrayField_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string arrayField = 2;</code>
         */
        public Builder addAllArrayField(
            java.lang.Iterable<java.lang.String> values) {
          ensureArrayFieldIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, arrayField_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string arrayField = 2;</code>
         */
        public Builder clearArrayField() {
          arrayField_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string arrayField = 2;</code>
         */
        public Builder addArrayFieldBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureArrayFieldIsMutable();
          arrayField_.add(value);
          onChanged();
          return this;
        }

        private int enumField_ = 0;
        /**
         * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions enumField = 3;</code>
         */
        public int getEnumFieldValue() {
          return enumField_;
        }
        /**
         * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions enumField = 3;</code>
         */
        public Builder setEnumFieldValue(int value) {
          enumField_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions enumField = 3;</code>
         */
        public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions getEnumField() {
          @SuppressWarnings("deprecation")
          com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions result = com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions.valueOf(enumField_);
          return result == null ? com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions.UNRECOGNIZED : result;
        }
        /**
         * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions enumField = 3;</code>
         */
        public Builder setEnumField(com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          enumField_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType.ProtoBufMultipleOptions enumField = 3;</code>
         */
        public Builder clearEnumField() {
          
          enumField_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType)
      }

      // @@protoc_insertion_point(class_scope:com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType)
      private static final com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType();
      }

      public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ProtoBufInnerType>
          PARSER = new com.google.protobuf.AbstractParser<ProtoBufInnerType>() {
        @java.lang.Override
        public ProtoBufInnerType parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtoBufInnerType(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ProtoBufInnerType> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ProtoBufInnerType> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int STRINGFIELD_FIELD_NUMBER = 1;
    private volatile java.lang.Object stringField_;
    /**
     * <code>string stringField = 1;</code>
     */
    public java.lang.String getStringField() {
      java.lang.Object ref = stringField_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringField_ = s;
        return s;
      }
    }
    /**
     * <code>string stringField = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringFieldBytes() {
      java.lang.Object ref = stringField_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOLEANFIELD_FIELD_NUMBER = 2;
    private boolean booleanField_;
    /**
     * <code>bool booleanField = 2;</code>
     */
    public boolean getBooleanField() {
      return booleanField_;
    }

    public static final int BYTESFIELD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString bytesField_;
    /**
     * <code>bytes bytesField = 3;</code>
     */
    public com.google.protobuf.ByteString getBytesField() {
      return bytesField_;
    }

    public static final int INTFIELD_FIELD_NUMBER = 4;
    private int intField_;
    /**
     * <code>int32 intField = 4;</code>
     */
    public int getIntField() {
      return intField_;
    }

    public static final int LONGFIELD_FIELD_NUMBER = 5;
    private long longField_;
    /**
     * <code>int64 longField = 5;</code>
     */
    public long getLongField() {
      return longField_;
    }

    public static final int FLOATFIELD_FIELD_NUMBER = 6;
    private float floatField_;
    /**
     * <code>float floatField = 6;</code>
     */
    public float getFloatField() {
      return floatField_;
    }

    public static final int DOUBLEFIELD_FIELD_NUMBER = 7;
    private double doubleField_;
    /**
     * <code>double doubleField = 7;</code>
     */
    public double getDoubleField() {
      return doubleField_;
    }

    public static final int MAPFIELD_FIELD_NUMBER = 8;
    private static final class MapFieldDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Double> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Double>newDefaultInstance(
                  com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_MapFieldEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.DOUBLE,
                  0D);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Double> mapField_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
    internalGetMapField() {
      if (mapField_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapFieldDefaultEntryHolder.defaultEntry);
      }
      return mapField_;
    }

    public int getMapFieldCount() {
      return internalGetMapField().getMap().size();
    }
    /**
     * <code>map&lt;string, double&gt; mapField = 8;</code>
     */

    public boolean containsMapField(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMapField().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapFieldMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Double> getMapField() {
      return getMapFieldMap();
    }
    /**
     * <code>map&lt;string, double&gt; mapField = 8;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Double> getMapFieldMap() {
      return internalGetMapField().getMap();
    }
    /**
     * <code>map&lt;string, double&gt; mapField = 8;</code>
     */

    public double getMapFieldOrDefault(
        java.lang.String key,
        double defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetMapField().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, double&gt; mapField = 8;</code>
     */

    public double getMapFieldOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetMapField().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int INNERFIELD_FIELD_NUMBER = 9;
    private com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType innerField_;
    /**
     * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
     */
    public boolean hasInnerField() {
      return innerField_ != null;
    }
    /**
     * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
     */
    public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType getInnerField() {
      return innerField_ == null ? com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.getDefaultInstance() : innerField_;
    }
    /**
     * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
     */
    public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerTypeOrBuilder getInnerFieldOrBuilder() {
      return getInnerField();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStringFieldBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stringField_);
      }
      if (booleanField_ != false) {
        output.writeBool(2, booleanField_);
      }
      if (!bytesField_.isEmpty()) {
        output.writeBytes(3, bytesField_);
      }
      if (intField_ != 0) {
        output.writeInt32(4, intField_);
      }
      if (longField_ != 0L) {
        output.writeInt64(5, longField_);
      }
      if (floatField_ != 0F) {
        output.writeFloat(6, floatField_);
      }
      if (doubleField_ != 0D) {
        output.writeDouble(7, doubleField_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMapField(),
          MapFieldDefaultEntryHolder.defaultEntry,
          8);
      if (innerField_ != null) {
        output.writeMessage(9, getInnerField());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStringFieldBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stringField_);
      }
      if (booleanField_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, booleanField_);
      }
      if (!bytesField_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, bytesField_);
      }
      if (intField_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, intField_);
      }
      if (longField_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, longField_);
      }
      if (floatField_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, floatField_);
      }
      if (doubleField_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, doubleField_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Double> entry
           : internalGetMapField().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
        mapField__ = MapFieldDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(8, mapField__);
      }
      if (innerField_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getInnerField());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType)) {
        return super.equals(obj);
      }
      com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType other = (com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType) obj;

      if (!getStringField()
          .equals(other.getStringField())) return false;
      if (getBooleanField()
          != other.getBooleanField()) return false;
      if (!getBytesField()
          .equals(other.getBytesField())) return false;
      if (getIntField()
          != other.getIntField()) return false;
      if (getLongField()
          != other.getLongField()) return false;
      if (java.lang.Float.floatToIntBits(getFloatField())
          != java.lang.Float.floatToIntBits(
              other.getFloatField())) return false;
      if (java.lang.Double.doubleToLongBits(getDoubleField())
          != java.lang.Double.doubleToLongBits(
              other.getDoubleField())) return false;
      if (!internalGetMapField().equals(
          other.internalGetMapField())) return false;
      if (hasInnerField() != other.hasInnerField()) return false;
      if (hasInnerField()) {
        if (!getInnerField()
            .equals(other.getInnerField())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STRINGFIELD_FIELD_NUMBER;
      hash = (53 * hash) + getStringField().hashCode();
      hash = (37 * hash) + BOOLEANFIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBooleanField());
      hash = (37 * hash) + BYTESFIELD_FIELD_NUMBER;
      hash = (53 * hash) + getBytesField().hashCode();
      hash = (37 * hash) + INTFIELD_FIELD_NUMBER;
      hash = (53 * hash) + getIntField();
      hash = (37 * hash) + LONGFIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongField());
      hash = (37 * hash) + FLOATFIELD_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getFloatField());
      hash = (37 * hash) + DOUBLEFIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDoubleField()));
      if (!internalGetMapField().getMap().isEmpty()) {
        hash = (37 * hash) + MAPFIELD_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMapField().hashCode();
      }
      if (hasInnerField()) {
        hash = (37 * hash) + INNERFIELD_FIELD_NUMBER;
        hash = (53 * hash) + getInnerField().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.riferrei.kafka.connect.pulsar.ProtoBufComplexType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.riferrei.kafka.connect.pulsar.ProtoBufComplexType)
        com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetMapField();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetMutableMapField();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.class, com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.Builder.class);
      }

      // Construct using com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        stringField_ = "";

        booleanField_ = false;

        bytesField_ = com.google.protobuf.ByteString.EMPTY;

        intField_ = 0;

        longField_ = 0L;

        floatField_ = 0F;

        doubleField_ = 0D;

        internalGetMutableMapField().clear();
        if (innerFieldBuilder_ == null) {
          innerField_ = null;
        } else {
          innerField_ = null;
          innerFieldBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_descriptor;
      }

      @java.lang.Override
      public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType getDefaultInstanceForType() {
        return com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.getDefaultInstance();
      }

      @java.lang.Override
      public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType build() {
        com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType buildPartial() {
        com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType result = new com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.stringField_ = stringField_;
        result.booleanField_ = booleanField_;
        result.bytesField_ = bytesField_;
        result.intField_ = intField_;
        result.longField_ = longField_;
        result.floatField_ = floatField_;
        result.doubleField_ = doubleField_;
        result.mapField_ = internalGetMapField();
        result.mapField_.makeImmutable();
        if (innerFieldBuilder_ == null) {
          result.innerField_ = innerField_;
        } else {
          result.innerField_ = innerFieldBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType) {
          return mergeFrom((com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType other) {
        if (other == com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.getDefaultInstance()) return this;
        if (!other.getStringField().isEmpty()) {
          stringField_ = other.stringField_;
          onChanged();
        }
        if (other.getBooleanField() != false) {
          setBooleanField(other.getBooleanField());
        }
        if (other.getBytesField() != com.google.protobuf.ByteString.EMPTY) {
          setBytesField(other.getBytesField());
        }
        if (other.getIntField() != 0) {
          setIntField(other.getIntField());
        }
        if (other.getLongField() != 0L) {
          setLongField(other.getLongField());
        }
        if (other.getFloatField() != 0F) {
          setFloatField(other.getFloatField());
        }
        if (other.getDoubleField() != 0D) {
          setDoubleField(other.getDoubleField());
        }
        internalGetMutableMapField().mergeFrom(
            other.internalGetMapField());
        if (other.hasInnerField()) {
          mergeInnerField(other.getInnerField());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object stringField_ = "";
      /**
       * <code>string stringField = 1;</code>
       */
      public java.lang.String getStringField() {
        java.lang.Object ref = stringField_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stringField_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stringField = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStringFieldBytes() {
        java.lang.Object ref = stringField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stringField = 1;</code>
       */
      public Builder setStringField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stringField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stringField = 1;</code>
       */
      public Builder clearStringField() {
        
        stringField_ = getDefaultInstance().getStringField();
        onChanged();
        return this;
      }
      /**
       * <code>string stringField = 1;</code>
       */
      public Builder setStringFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stringField_ = value;
        onChanged();
        return this;
      }

      private boolean booleanField_ ;
      /**
       * <code>bool booleanField = 2;</code>
       */
      public boolean getBooleanField() {
        return booleanField_;
      }
      /**
       * <code>bool booleanField = 2;</code>
       */
      public Builder setBooleanField(boolean value) {
        
        booleanField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool booleanField = 2;</code>
       */
      public Builder clearBooleanField() {
        
        booleanField_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytesField_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bytesField = 3;</code>
       */
      public com.google.protobuf.ByteString getBytesField() {
        return bytesField_;
      }
      /**
       * <code>bytes bytesField = 3;</code>
       */
      public Builder setBytesField(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bytesField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bytesField = 3;</code>
       */
      public Builder clearBytesField() {
        
        bytesField_ = getDefaultInstance().getBytesField();
        onChanged();
        return this;
      }

      private int intField_ ;
      /**
       * <code>int32 intField = 4;</code>
       */
      public int getIntField() {
        return intField_;
      }
      /**
       * <code>int32 intField = 4;</code>
       */
      public Builder setIntField(int value) {
        
        intField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intField = 4;</code>
       */
      public Builder clearIntField() {
        
        intField_ = 0;
        onChanged();
        return this;
      }

      private long longField_ ;
      /**
       * <code>int64 longField = 5;</code>
       */
      public long getLongField() {
        return longField_;
      }
      /**
       * <code>int64 longField = 5;</code>
       */
      public Builder setLongField(long value) {
        
        longField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 longField = 5;</code>
       */
      public Builder clearLongField() {
        
        longField_ = 0L;
        onChanged();
        return this;
      }

      private float floatField_ ;
      /**
       * <code>float floatField = 6;</code>
       */
      public float getFloatField() {
        return floatField_;
      }
      /**
       * <code>float floatField = 6;</code>
       */
      public Builder setFloatField(float value) {
        
        floatField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float floatField = 6;</code>
       */
      public Builder clearFloatField() {
        
        floatField_ = 0F;
        onChanged();
        return this;
      }

      private double doubleField_ ;
      /**
       * <code>double doubleField = 7;</code>
       */
      public double getDoubleField() {
        return doubleField_;
      }
      /**
       * <code>double doubleField = 7;</code>
       */
      public Builder setDoubleField(double value) {
        
        doubleField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double doubleField = 7;</code>
       */
      public Builder clearDoubleField() {
        
        doubleField_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Double> mapField_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
      internalGetMapField() {
        if (mapField_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MapFieldDefaultEntryHolder.defaultEntry);
        }
        return mapField_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
      internalGetMutableMapField() {
        onChanged();;
        if (mapField_ == null) {
          mapField_ = com.google.protobuf.MapField.newMapField(
              MapFieldDefaultEntryHolder.defaultEntry);
        }
        if (!mapField_.isMutable()) {
          mapField_ = mapField_.copy();
        }
        return mapField_;
      }

      public int getMapFieldCount() {
        return internalGetMapField().getMap().size();
      }
      /**
       * <code>map&lt;string, double&gt; mapField = 8;</code>
       */

      public boolean containsMapField(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMapField().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMapFieldMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Double> getMapField() {
        return getMapFieldMap();
      }
      /**
       * <code>map&lt;string, double&gt; mapField = 8;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Double> getMapFieldMap() {
        return internalGetMapField().getMap();
      }
      /**
       * <code>map&lt;string, double&gt; mapField = 8;</code>
       */

      public double getMapFieldOrDefault(
          java.lang.String key,
          double defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Double> map =
            internalGetMapField().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, double&gt; mapField = 8;</code>
       */

      public double getMapFieldOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Double> map =
            internalGetMapField().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMapField() {
        internalGetMutableMapField().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, double&gt; mapField = 8;</code>
       */

      public Builder removeMapField(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMapField().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Double>
      getMutableMapField() {
        return internalGetMutableMapField().getMutableMap();
      }
      /**
       * <code>map&lt;string, double&gt; mapField = 8;</code>
       */
      public Builder putMapField(
          java.lang.String key,
          double value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableMapField().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, double&gt; mapField = 8;</code>
       */

      public Builder putAllMapField(
          java.util.Map<java.lang.String, java.lang.Double> values) {
        internalGetMutableMapField().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType innerField_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType, com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.Builder, com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerTypeOrBuilder> innerFieldBuilder_;
      /**
       * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
       */
      public boolean hasInnerField() {
        return innerFieldBuilder_ != null || innerField_ != null;
      }
      /**
       * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
       */
      public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType getInnerField() {
        if (innerFieldBuilder_ == null) {
          return innerField_ == null ? com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.getDefaultInstance() : innerField_;
        } else {
          return innerFieldBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
       */
      public Builder setInnerField(com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType value) {
        if (innerFieldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          innerField_ = value;
          onChanged();
        } else {
          innerFieldBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
       */
      public Builder setInnerField(
          com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.Builder builderForValue) {
        if (innerFieldBuilder_ == null) {
          innerField_ = builderForValue.build();
          onChanged();
        } else {
          innerFieldBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
       */
      public Builder mergeInnerField(com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType value) {
        if (innerFieldBuilder_ == null) {
          if (innerField_ != null) {
            innerField_ =
              com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.newBuilder(innerField_).mergeFrom(value).buildPartial();
          } else {
            innerField_ = value;
          }
          onChanged();
        } else {
          innerFieldBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
       */
      public Builder clearInnerField() {
        if (innerFieldBuilder_ == null) {
          innerField_ = null;
          onChanged();
        } else {
          innerField_ = null;
          innerFieldBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
       */
      public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.Builder getInnerFieldBuilder() {
        
        onChanged();
        return getInnerFieldFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
       */
      public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerTypeOrBuilder getInnerFieldOrBuilder() {
        if (innerFieldBuilder_ != null) {
          return innerFieldBuilder_.getMessageOrBuilder();
        } else {
          return innerField_ == null ?
              com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.getDefaultInstance() : innerField_;
        }
      }
      /**
       * <code>.com.riferrei.kafka.connect.pulsar.ProtoBufComplexType.ProtoBufInnerType innerField = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType, com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.Builder, com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerTypeOrBuilder> 
          getInnerFieldFieldBuilder() {
        if (innerFieldBuilder_ == null) {
          innerFieldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType, com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerType.Builder, com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType.ProtoBufInnerTypeOrBuilder>(
                  getInnerField(),
                  getParentForChildren(),
                  isClean());
          innerField_ = null;
        }
        return innerFieldBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.riferrei.kafka.connect.pulsar.ProtoBufComplexType)
    }

    // @@protoc_insertion_point(class_scope:com.riferrei.kafka.connect.pulsar.ProtoBufComplexType)
    private static final com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType();
    }

    public static com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoBufComplexType>
        PARSER = new com.google.protobuf.AbstractParser<ProtoBufComplexType>() {
      @java.lang.Override
      public ProtoBufComplexType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoBufComplexType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoBufComplexType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoBufComplexType> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.riferrei.kafka.connect.pulsar.ProtoBufGenComplexType.ProtoBufComplexType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_MapFieldEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_MapFieldEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_ProtoBufInnerType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_ProtoBufInnerType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021complexType.proto\022!com.riferrei.kafka." +
      "connect.pulsar\"\242\005\n\023ProtoBufComplexType\022\023" +
      "\n\013stringField\030\001 \001(\t\022\024\n\014booleanField\030\002 \001(" +
      "\010\022\022\n\nbytesField\030\003 \001(\014\022\020\n\010intField\030\004 \001(\005\022" +
      "\021\n\tlongField\030\005 \001(\003\022\022\n\nfloatField\030\006 \001(\002\022\023" +
      "\n\013doubleField\030\007 \001(\001\022V\n\010mapField\030\010 \003(\0132D." +
      "com.riferrei.kafka.connect.pulsar.ProtoB" +
      "ufComplexType.MapFieldEntry\022\\\n\ninnerFiel" +
      "d\030\t \001(\0132H.com.riferrei.kafka.connect.pul" +
      "sar.ProtoBufComplexType.ProtoBufInnerTyp" +
      "e\032/\n\rMapFieldEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\001:\0028\001\032\226\002\n\021ProtoBufInnerType\022\023\n\013doub" +
      "leField\030\001 \001(\001\022\022\n\narrayField\030\002 \003(\t\022s\n\tenu" +
      "mField\030\003 \001(\0162`.com.riferrei.kafka.connec" +
      "t.pulsar.ProtoBufComplexType.ProtoBufInn" +
      "erType.ProtoBufMultipleOptions\"c\n\027ProtoB" +
      "ufMultipleOptions\022\020\n\014FIRST_OPTION\020\000\022\021\n\rS" +
      "ECOND_OPTION\020\001\022\020\n\014THIRD_OPTION\020\002\022\021\n\rFOUR" +
      "TH_OPTION\020\003B\030B\026ProtoBufGenComplexTypeb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_descriptor,
        new java.lang.String[] { "StringField", "BooleanField", "BytesField", "IntField", "LongField", "FloatField", "DoubleField", "MapField", "InnerField", });
    internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_MapFieldEntry_descriptor =
      internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_descriptor.getNestedTypes().get(0);
    internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_MapFieldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_MapFieldEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_ProtoBufInnerType_descriptor =
      internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_descriptor.getNestedTypes().get(1);
    internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_ProtoBufInnerType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_riferrei_kafka_connect_pulsar_ProtoBufComplexType_ProtoBufInnerType_descriptor,
        new java.lang.String[] { "DoubleField", "ArrayField", "EnumField", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
